import Head from 'next/head';
import styled from 'styled-components';

const Wrapper = styled.div(({ theme }) => ({
  width: '100%',
  maxWidth: '620px',
  padding: '0 20px',
  margin: '0 auto',

  [`@media (min-width: ${theme.breakpoints.md}px)`]: {
    transform: 'translateX(-50px)',
  },
}));

const Layout: React.FC = ({ children }) => (
  <Wrapper>
    <Head>
      <link rel='preload' href='/fonts/Vremena/Book.woff' as='font' type='font/woff2' crossOrigin='' />
      <link rel='preload' href='/fonts/Vremena/Medium.woff' as='font' type='font/woff2' crossOrigin='' />
      <title>Bartłomiej Jacak — Digital Creator</title>
      {/* <meta name='description' content='Generated by create next app' /> */}
      {/* <link rel='icon' href='/favicon.ico' /> */}
    </Head>
    {children}
  </Wrapper>
);

export default Layout;
